# Numpy
### mathematical computation
it works on arrays : most advanced list

In [1]:
import numpy as np

In [2]:
my_list = [1,3,4]
my_list

[1, 3, 4]

In [3]:
array = np.array(my_list)
print(type(array),array)

<class 'numpy.ndarray'> [1 3 4]


In [4]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
new = np.array(my_matrix)
print(new)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# list comprehension : defining methods 
l = [i for i in range(10)]
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


### np.arange(start,stop,step)
np.arange() is used to print an array of numbers in the given range with excluding last item . it is like range function in python.

In [6]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### np.zeros() and np.ones()

In [7]:
# zeros and ones 
a = np.zeros(3)
b = np.ones(2)
print(a,b)

[0. 0. 0.] [1. 1.]


In [8]:
c = np.zeros((5,5))
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### np.linspace()
np.linspace() : linear space b/w elements

In [9]:
s = np.linspace(0,10,3)
print(s)

[ 0.  5. 10.]


In [10]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

### np.eye()
 it produces a identity matrix means matrix of 0 and 1 with 1 on the diagonal

In [11]:
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## random in numpy

### np.random.rand()
it generates random number its default range is b/w 0 and 1 but close to 0

In [12]:
p = np.random.rand(4)
print(p)

[0.286263   0.25060593 0.09419746 0.18618617]


In [13]:
a = np.random.rand(4,4)
print(a)

[[0.40356983 0.83807317 0.95983144 0.0434285 ]
 [0.25432248 0.31028023 0.26095606 0.43130985]
 [0.36773798 0.45222075 0.36258994 0.48630456]
 [0.15292004 0.2940609  0.57394038 0.17124016]]


### np.random.randn()
it generates numbers but more likely to be negative and also try to maintain the space

In [14]:
a = np.random.randn(2)
print(a)

[-0.27396002  1.34301702]


In [15]:
c = np.random.randn(4,4)
print(c)

[[-0.65381689 -0.06036763 -0.81062265 -0.32208369]
 [-1.47783873 -0.0118482   0.95114333 -3.02687603]
 [-1.10608166  2.22299744 -0.97073658  0.3693973 ]
 [ 0.0598847  -0.74226345 -0.67220286  1.60799773]]


### np.random.randint(start,stop,how many no.)
it generates a random integer between the range

In [16]:
p =np.random.randint(1,100)
print(p)

95


In [17]:
s = np.random.randint(1,100,10)
print(s)

[44 72 35 64 45 63  2 17  2 81]


In [18]:
# seed 
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [19]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

### reshape(rows,columns)
it is used to change the shape of an existing array

In [21]:
# matrix : random number b/w 0 ,50 of 10 num

arr = np.arange(25)
rarr = np.random.randint(0,50,10)
print(arr)
print(rarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[38 18 22 10 10 23 35 39 23  2]


In [22]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [23]:
rarr.reshape(2,5)

array([[38, 18, 22, 10, 10],
       [23, 35, 39, 23,  2]], dtype=int32)

In [24]:
rarr.reshape(5,2)

array([[38, 18],
       [22, 10],
       [10, 23],
       [35, 39],
       [23,  2]], dtype=int32)

In [25]:
rarr.max()

np.int32(39)

In [26]:
rarr.min()

np.int32(2)

In [27]:
rarr.argmax()  # index of max

np.int64(7)

In [28]:
rarr.argmin()  # index of min

np.int64(9)

### .shape
it gives the shape of array

In [29]:
arr.shape

(25,)

In [30]:
arr.reshape(5,5).shape

(5, 5)

In [31]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### indexing and slicing

In [32]:
arr = np.arange(10,20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]


In [33]:
arr[6]

np.int64(16)

In [34]:
arr[0:3]

array([10, 11, 12])

In [35]:
arr[0:6:2]

array([10, 12, 14])

### broadcasting

In [36]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [37]:
slice_arr = arr[0:5]
print(slice_arr)

[0 1 2 3 4]


In [38]:
slice_arr[0] = 99
print(slice_arr)

[99  1  2  3  4]


In [39]:
slice_arr[:] = 99
print(slice_arr)

[99 99 99 99 99]


In [40]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [41]:
# copy()
arr_copy = arr.copy()
print(arr_copy)

[99 99 99 99 99  5  6  7  8  9]


In [42]:
arr_copy[:4] = 45
print(arr_copy)

[45 45 45 45 99  5  6  7  8  9]


In [43]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

### 2D array 

In [2]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
arr[2]

array([7, 8, 9])

In [46]:
arr[2][2]

np.int64(9)

#### 2d array slicing

In [47]:
arr[:2,:2]

array([[1, 2],
       [4, 5]])

In [48]:
arr[:2,1:]

array([[2, 3],
       [5, 6]])

## conditional statements

In [3]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [50]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [51]:
arr<6

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [52]:
arr==7

array([False, False, False, False, False, False,  True, False, False,
       False])

In [53]:
arr !=5

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
        True])

In [54]:
a = arr[arr>4]
print(a)

[ 5  6  7  8  9 10]


### numpy operations

In [55]:
l1 =[1,2,3]
l2 = [4,5,6]
l3 = l1+l2
print(l3)

[1, 2, 3, 4, 5, 6]


In [56]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
arr +arr # addition

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
arr -arr # subtraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
arr *arr # multiplication

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [60]:
arr/arr # division

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [61]:
arr*3

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [4]:
arr2 = arr**2
arr2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [63]:
np.sqrt(arr2) # square root  cbrt() for cube root

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

exponent : 1.0000E+2 : scientific number datatype

In [64]:
np.exp(arr2)

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06,
       7.20048993e+10, 4.31123155e+15, 1.90734657e+21, 6.23514908e+27,
       1.50609731e+35, 2.68811714e+43])

In [65]:
# sin cos tan
np.sin(arr2)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332, -0.13235175,
       -0.99177885, -0.95375265,  0.92002604, -0.62988799, -0.50636564])

In [66]:
np.cos(arr2)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948,  0.99120281,
       -0.12796369,  0.30059254,  0.39185723,  0.77668598,  0.86231887])

In [67]:
np.tan(arr2)

array([ 1.55740772,  1.15782128, -0.45231566,  0.30063224, -0.13352641,
        7.75047091, -3.17290855,  2.34786031, -0.81099442, -0.58721392])

In [69]:
#log 
np.log(arr2)

array([0.        , 1.38629436, 2.19722458, 2.77258872, 3.21887582,
       3.58351894, 3.8918203 , 4.15888308, 4.39444915, 4.60517019])

 statistic functions in numpy : sum,max,mean,min

In [70]:
np.sum(arr2)

np.int64(385)

In [71]:
np.mean(arr2)

np.float64(38.5)

In [5]:
# standard deviation
np.std(arr2)

np.float64(32.41990129534635)

In [72]:
np.max(arr2)

np.int64(100)

In [73]:
np.min(arr2)

np.int64(1)

In [5]:
arr = np.array(([1,2,3],[4,5,6],[7,8,9]))
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [76]:
np.sum(arr)

np.int64(45)

axis = 0 : means rows and axis = 1 : columns

In [78]:
arr.sum(axis=0)

array([12, 15, 18])

In [79]:
arr.sum(axis=1)

array([ 6, 15, 24])

In [80]:
arr.shape

(3, 3)